services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_DB: "curso_dev"
      POSTGRES_PASSWORD: "cursodev"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
